name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      dockerComposeFile:
        description: 'Docker Compose file'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run Docker Compose
      run: docker-compose -f ${{ github.event.inputs.dockerComposeFile }} up -d

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies and run tests
      run: |
        pip install -r requirements.txt
        pytest test1.py
